version: '3.8'
services:
  # Elasticsearch Servisi
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    hostname: "elastic"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - hotel-network

  # Kibana Servisi
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
    networks:
      - hotel-network

  # RabbitMQ Servisi
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5673:5672"  # Mesajlaşma portu
      - "15673:15672"  # Yönetim paneli portu
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hotel-network

  # PostgreSQL Servisi
  hotel-postgres:
    image: postgres:latest
    container_name: hotel-postgres
    hostname: "hotel"
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
      POSTGRES_DB: hoteldb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel-network

volumes:
  es_data:
    driver: local
  rabbitmq_data:
    driver: local
  postgres_data:
    driver: local

networks:
  hotel-network:
    driver: bridge
